title: Seite

fields:
  
  prevnext_top: prevnext

###############################################

  content_tab: content/tab

  title: content/title

  text:  content/text_markdown

###############################################

  prevnext_bottom: prevnext
